[upstox]
access_token="eyJ0eXAiOiJKV1QiLCJrZXlfaWQiOiJza192MS4wIiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiI0Q0NXRzciLCJqdGkiOiI2OTFiOGY0MmVmNjIyNjBhYTYwNDI4MzQiLCJpc011bHRpQ2xpZW50IjpmYWxzZSwiaXNQbHVzUGxhbiI6dHJ1ZSwiaWF0IjoxNzYzNDEzODI2LCJpc3MiOiJ1ZGFwaS1nYXRld2F5LXNlcnZpY2UiLCJleHAiOjE3NjM0MTY4MDB9.HigzZgn1sUxdSDqyESFgDXW6CCzkJiM7BcfkNZqpkTE"
api_key="d01c59be-8f1a-46b5-9094-131bcdd05e7b"
api_secret="v6oo0uqmow"
redirect_uri="https://marketmarketmavericksoptionchain.streamlit.app"